version: '3.7'

services:
  proxitok-web:
    container_name: proxitok-web
    hostname: proxitok-web
    image: ghcr.io/pablouser1/proxitok:latest
    restart: always
    ports:
      - '127.0.0.1:8087:8080'
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok-redis
      - REDIS_PORT=6379
      - API_SIGNER=remote
      - API_SIGNER_URL=http://proxitok-signer:8080/signature
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - proxitok-redis
      - proxitok-signer
    networks:
      - proxitok
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  proxitok-redis:
    container_name: proxitok-redis
    hostname: proxitok-redis
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    networks:
      - proxitok
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL

  proxitok-signer:
    container_name: proxitok-signer
    hostname: proxitok-signer
    image: ghcr.io/pablouser1/signtok:latest
    init: true
    networks:
      - proxitok
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  proxitok-cache:

networks:
  proxitok:
